### ISSUE TITLE
Switch to publishing snapshots from master, and versions from tags

### ISSUE THREAD

**Issue by d-led** [vlingo/vlingo-actors#17]
This is WIP

## Current state

- experiment via the [`snapshots`](https://github.com/vlingo/vlingo-actors/tree/snapshots) branch
- Sonatype credentials : `SONATYPE_PASSWORD`, `SONATYPE_USERNAME` should be entered either via the config: https://travis-ci.org/vlingo/vlingo-actors/settings or the `travis` CLI encrypted variables inside `.travis.yml` 
- once publishing snapshots works, the master deployment configuration should be switched to tags: see [deployment docs](https://docs.travis-ci.com/user/deployment)
- when the branch `snapshots` is merged, and snapshots are set to master, and will always represent "the next" version, unlike now, where the same, current version is pushed on every build
- tagging a release should trigger a fixed "next" version pull
- `vlingo-platform` gradle scripts will probably have to be updated with adjusted regexes to take into account that the version in `pom.xml` will now end in `-SNAPSHOT` 

## Safety considerations

- Travis-CI seems to protect against leaking credentials from pull requests from outside the repository
- Given a limited number of committers, this might be secure enough
- Protected variables get scraped from the log output
- Potential pull request attacker could try dump the environment variables somewhere else, but if Travis-CI is diligent, this should not happen on pull requests from outside the repo:

https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions

> The most important restriction for pull requests is about secure environment variables and encrypted data.
> 
> A pull request sent from a fork of the upstream repository could be manipulated to expose environment variables. The upstream > repository’s maintainer would have no protection against this attack, as pull requests can be sent by anyone who forks the > repository on GitHub.> 
> 
> **Travis CI makes encrypted variables and data available only to pull requests coming from the same repository**. These are > considered trustworthy, as only members with write access to the repository can send them.> 
> 
> _Pull requests sent from forked repositories do not have access to encrypted variables or data_.

### Sonatype tokens

- in order to not compromise log in credentials, there's an option to generate a token, and a matching username at https://oss.sonatype.org/#profile;User%20Token

![token](https://user-images.githubusercontent.com/1716584/45258726-44d80a00-b3bd-11e8-8da0-fd2519bac93b.png)

**Comment by d-led** [comment]
@VaughnVernon 

there's some progress. I generated a token for myself, and configured it on travis. The repo ID seems to be `oss-snapshots`, as seen in `pom.xml`.

Before, the response was: `Unauthorized`

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project vlingo-actors: Failed to deploy artifacts: Could not transfer artifact io.vlingo:vlingo-actors:jar:0.6.1-20180908.211533-1 from/to oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/io/vlingo/vlingo-actors/0.6.1-SNAPSHOT/vlingo-actors-0.6.1-20180908.211533-1.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
```

currently: `Forbidden`, which sounds like progress

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project vlingo-actors: Failed to deploy artifacts: Could not transfer artifact io.vlingo:vlingo-actors:jar:0.6.1-20180908.212217-1 from/to oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): Access denied to: https://oss.sonatype.org/content/repositories/snapshots/io/vlingo/vlingo-actors/0.6.1-SNAPSHOT/vlingo-actors-0.6.1-20180908.212217-1.jar, ReasonPhrase: Forbidden. -> [Help 1]
```

Next step: 
- try with your token
- if that fails, resort to Jira

**Comment by d-led** [comment]
https://issues.sonatype.org/browse/OSSRH-45028

**Comment by VaughnVernon** [comment]
I have made all the adjustments in Travis for Sonatype auth.  I saw that the vlingo-actors@snapshot build worked, but I don't see the snapshot artifact anywhere (checked Sonatype and then Bintray).

In case we need more help.
https://groups.google.com/a/glists.sonatype.com/forum/#!forum/ossrh-users

**Comment by d-led** [comment]
it still doesn't seem to work. The POM looks right, and other projects use the same nodes in the XML, but still. Dunno, if the credentials are passed correctly

**Comment by d-led** [comment]
ok, progress: `Skipping a deployment with the bintray provider because this branch is not permitted: snapshots`

**Comment by VaughnVernon** [comment]
I wonder if we must request a new artifact name for Sonatype. Whenever I need to sync a new repo artifacts from Bintray to Sonatype, Bintray requires that we must request this from Sonatype. Thing is, I don't see the new artifact on Bintray (what would the name be?).

**Comment by d-led** [comment]
we'll need to at least it into master.. it seems, snapshots are only allowed from there. Then we'll see

**Comment by d-led** [comment]
next challenge:

```
[Bintray Upload] Reading descriptor file: bintray.json
[Bintray Upload] Uploading file 'target/vlingo-actors-0.7.5-SNAPSHOT-javadoc.jar' to /io/vlingo/vlingo-actors/0.7.5/vlingo-actors-0.7.5-SNAPSHOT-javadoc.jar
[Bintray Upload] Bintray response: 400 Bad Request. Snapshot versions are not supported.
[Bintray Upload] Uploading file 'target/vlingo-actors-0.7.5-SNAPSHOT-sources.jar' to /io/vlingo/vlingo-actors/0.7.5/vlingo-actors-0.7.5-SNAPSHOT-sources.jar
[Bintray Upload] Bintray response: 400 Bad Request. Snapshot versions are not supported.
[Bintray Upload] Uploading file 'target/vlingo-actors-0.7.5-SNAPSHOT.jar' to /io/vlingo/vlingo-actors/0.7.5/vlingo-actors-0.7.5-SNAPSHOT.jar
[Bintray Upload] Bintray response: 400 Bad Request. Snapshot versions are not supported.
[Bintray Upload] Uploading file 'pom.xml' to /io/vlingo/vlingo-actors/0.7.5/vlingo-actors-0.7.5.pom
[Bintray Upload] Bintray response: 201 Created. success
[Bintray Upload] Signing version with no passphrase...
[Bintray Upload] Bintray response: 200 OK. success
[Bintray Upload] Publishing version '0.7.5' of package 'vlingo-actors'...
[Bintray Upload] Bintray response: 200 OK. 
```

**Comment by d-led** [comment]
got a spare minute and tried an alternative provier: https://packagecloud.io/docs#maven_deploy

the free plan is kind of limited (250mb), but at least it worked out of the box via gradle. I just followed the gradle instructions, and the snapshot build got published: https://packagecloud.io/dled/dled/packages/java/dled.java.experiments/dled.java.experiments-0.0.1-SNAPSHOT.jar

source: https://github.com/d-led/dled.java.experiments

**Comment by d-led** [comment]
resulting packages on packagecloud:
![Screen Shot 2019-03-17 at 10 57 51](https://user-images.githubusercontent.com/1716584/54488588-b8466100-48a3-11e9-8e6a-4d06f468064e.png)

release built triggered via creating a branch
![Screen Shot 2019-03-17 at 10 58 02](https://user-images.githubusercontent.com/1716584/54488589-b8466100-48a3-11e9-865c-8ae999b324cd.png)

snapshot build triggered via a commit
![Screen Shot 2019-03-17 at 10 58 18](https://user-images.githubusercontent.com/1716584/54488591-b8def780-48a3-11e9-8bcd-887cdc9848d2.png)

The build is split into stages, which are conditional (`.travis.yml`):

```yaml
stages:
  - name: build
  - name: snapshot
    if: branch = master
  - name: example
    if: branch = master
  - name: release
    if: tag =~ ^v\d
```

**Comment by d-led** [comment]
halting the packagecloud effort, as 250mb storage and bandwidth might be too limiting

**Comment by VaughnVernon** [comment]
Comment by from gitter:

https://gitter.im/vlingo-platform-java/actors?at=5ca9ee9525686a7dc3ee0679

Copied text follows.

=====================================

I suggested to change the new version to SNAPSHOT after release. As I do not know what you want and how deep your knowledge is, here a short summary of my knowledge about "how to release". As you can see there are (as always) alternatives. Before starting to work on something concrete, it should be clear where you want to point your "I want this" finger, too ;-) Will be away the rest of the day...:-/

A release process in a context of a Java/Maven based infrastructure (likely similar for gradle) is normally as follows:

Precondition:

You have all artefacts in a SNAPSHOT version. This assures that build artefacts with a snapshot version are not published by accident. Maven also handles snapshot versions slightly different (caching).
You also have the internal dependencies on this same versions.
Nothing is checked out (clean repository). Ideally you start with a fresh checkout.
I assume that cyclic dependencies would be a problem. Also if you have multiple artefacts (as you have with vlingo-xxx), you should process them in dependency order, so this order must be defined (implicitely).
Internal dependencies can be clearly identified by explicitely naming them or via a common group id.
You work on master, no branching is required explicitely. Things would be more complex if you would want to create patch versions. If you will do in future, you should make sure that all operations work branch-relative.
Step 1, actual release of new version:

You change all versions to the next (major, minor) version (in the simplest case this is just the current version without SNAPSHOT). You could either let maven find out the next (minor, major) version itself or you can define the next version yourself.
You also change the dependencies on your own artefacts to the new version, to get a new consistent state.
You build this new version and execute all tests (loop over all artefacts in dependency order, if the order is wrong you will get something like "dependency x.y not found"). If somethings fails, build is aborted and all local changes are either reverted or the checkout thrown away completely. This build should also rebuild all stuff that contains the new version (for exmaple using templating for text files in maven).
You check in this new version (and optional tag it in git).
You then publish the build results to maven central, update the web page and similar. If this fails, you have a transaction problem :-/ You could thus do this step before the previous as the current step can possibly be repeated easier on technical errors.
Step 2, create new snapshot version:

You the change the version of your artefacts and internal dependencies again to the next minor snapshot version (not that you still decide later that the next release wil be a major release, the SNAPSHOT version just assures that you do not mix artefacts of different version uncontrolled).
You optionally build again, if you want to publish the new snapshot version. There should be no build or test errors, else your first goal would be to fix this!
You check in the new snapshot version.
In result everybody that updates master now will work with the new snapshot version of everything.
POM manipulation can be done using maven versions plugin: https://www.mojohaus.org/versions-maven-plugin/plugin-info.html

Concrete maven targets to use depend on:

Will every artefact always have the same version (currently yes)?
Do you want to store dependency version in a maven POM property or explicit in the dependency itself? The first is simpler but you have to handle versioning (and incrementing versions) yourself, in the second maven might be able update the POM to the next snapshot version itself.
Do you build all artefacts in the same multi-module build or separately (currently you use the second approach, which forces you to handle dependency order yourself)?
The release plugin of maven does all steps (without fixing dependency versions) automatically, but it would do so for each artefact yourself. IMHO it is OK for simple builds, but a more manu

**Comment by Framstag** [comment]
Still thinking about it:

The current structure of the code is:
* vlingo-platform which contains the actual build/release stuff
* vlingo-xxx a number of  base and extension modules

Each project has its own git (github) repository. 

There are multiple types of builds (either currently implemented or potential useful):
* Central build/test on each checking => Build /test errors should immediately (manually) result in an issue and incident handling. Build has no external effects (no upload of snapshot). This is the CI pipeline.
* Snapshot builds (if build or test fails, see above) => How are these currently triggered? Should be they the same as the "on each checkin" builds. Are they different?
* Release builds => See above regarding potential release magic

How should the "on each checkin" builds actually work? They either checkout everything else and build and test it locally, or the can only build the repository code itself and get the other modules via dependency.  This would require that the "on each checkin" builds push their build result as snapshot into some registry in the end. In the first case, this would use the same "build everything" code as in the platform module.

Another point: Currently if you look at the github repository on github none of the modules has an release. Without a release there are also no release notes and no release artefacts. In Case of Java the artefacts can be found in a global maven registry, but still it would be nice... See https://github.com/spring-projects/spring-boot/releases for an example (still lacking download of build artefacts).

If one looks at https://developer.github.com/v3/repos/releases/#create-a-release, it looks like releases can be created manually. So perhaps we release the platform module manually, and the build of the platform project then just triggers releases of all other modules? And the modules release themselfs.

Because of all that the setup of @d-led possibly is too simple for a test? We would at least need three repositories (e.g. platform, base and extension) to test different approaches...

But before that:
* Which build types are required?
* How much explicit support of github regarding releases do you want to use?

**Comment by lskillen** [comment]
Hello! @cloudsmith-io can help with hosting of snapshots (or releases), and you don't need to apply for an open source account. Just create an open source repository and away you go. You shouldn't have any issues with limitations. 

Disclaimer: I work for Cloudsmith. :)

**Comment by wwerner** [comment]
Necromancing this issue. A bit long, sorry.

From what I learned from the discussions on slack and my experience setting up my vlingo dev environment, we currently have these challenges/issues/open questions regarding building and releasing:

1. No real `-SNAPSHOT` builds - Forces developers to build the complete platform locally quite often, as there are many changes and outdated versions (with the _same_ version number) are locally cached in `.m2/repository`. `mvn clean` does _not_ purge the local cache. When building docker images, the dependencies might be additionally cached in a separate docker layer, which also leads to builds using outdate libraries.
2. There is an ongoing discussion whether to merge the modules into one repository. 
3. Releases: I haven't found whether we decided to version the platform w/ all modules as a whole (simple and convenient, but breaks semantic versioning on the modules) or whether to use a `BOM`

Not sure if there is more, please do correct me if I forgot or misinterpreted stuff.

Here's my take on these:
1. IMHO, this is absolutely required. 
1.1. Contributors will often work with only a subset of the modules. Building & testing the complete platform takes quite some time and isn't 100% self-explanatory, so potiential contributers might be scared away.
1.2 Multiple contributors may churn a lot of code and if everyone is working on `master` often (as currently seems to be the case), many people will get bitten by broken builds or intermediate versions. 
`-SNAPSHOTS` kinda solve this, at least for the modules one is not actively working on.
2. I'd vote against one big repository, for essentially the same reasons stated in 1.1 and 1.2.
2.1 Having all modules at hand in one project makes it easy to (perhaps inadvertendly) make far reaching changes. This can increase speed at the beginning, but bears the risk of blurring the module's boundaries. A separate project makes the different concerns visible more clearly.
2.2 Different projects have different dependencies. I don't really want to spin up containers for postgres, rabbitmq, geode and whatnot if I only want to make a small change and run the tests (see 1.1 again)
2.3 If you need to work on most of the modules at the same time, you can always manage them as one project in your IDE anyway, regardless of whether they com from one or many repos.
3. I'd let each module evolve at its own pace and use semantic versions. `vlingo-platform` should be responsible for maintaining the `BOM` for specific versions. IIRC, this is also how the Spring guys do it, btw.
3.1. The `versions` and `release` maven plugins can help quite a bit here. This is a fairly process standardized in maven. (yes, I don't hate maven ;-). I cursed it often enough, but I think our issues match mvn's standard process very well)
3.2 The module versions comprising a `vlingo-platform` release need to be maintained in the platform BOM pom (🥁)


And here's what I think would work:
* Keep all modules in separate projects with separate builds, but have them import common dependencies from a platform parent pom
* Add a BOM pom in platform, containing all modules for a release
* Use mvn release to manage updating the versions and pushing the artifacts. This needs to be possible per project but also form `platform` for all projects (either per scripts or per parent pom)
* Always tag and branch off releases
* Master should always be on `<next version>-SNAPSHOT` and be dependent on the resp. `-SNAPSHOT`s of the modules
* mvn release fails the build if there are still `SNAPSHOT` dependencies, this adds a nice safety net
* all release tasks can be run within a CI build, so a release is basically only creaing `release/` branch (_if_ we want this, the build would need our signing keys. We used an encrypted keybase (http://keybase.io) git repo to make sensitive information like this available to the build; but perhaps there are better solutions)

This essentially separates the `build` part (the poms in the modules) from the `release` part (the BOM pom in `platform`).

What we would need for that:
* maven central release and snapshot repositories
* their signing keys

Drawbacks:
* Refactoring the build typically hurts everyone at least for a little time
* Git and Maven versions are not kept in sync automatically

If you have read this far, what do you think?

**Comment by VaughnVernon** [comment]
What @wwerner has put together is very well thought out and takes this discussion farther than it's previously gone. Thanks!

We need to have broader input from others, not only from a prior experience PoV but also from where we are and what we need to accomplish. @kmruiz and I discussed having a team meeting. I am sure we could find a time for everyone's timezone and I am quite flexible myself (I can make just about any time work).

I am concerned that we have had no volunteers step up to this with an absolute answer as to how it should be done. So far it's been speculative ideas of how it might work, but with no success. This is not a criticism, just fact. We are all doing the best we can and hopefully all of us recognize that in each contributor's efforts. Yet, I don't want us to continue on the same path of hopeful-guessing and dedicating large amounts of time to this and not reach a favorable outcome.

So, I have put together my thoughts in priority order:

1. Wolfgang, if I have misunderstood you and you have done this successfully in the way you stated, please correct me.
2. Has anyone actually done this successfully using the same components of our current CI pipeline?
3. Does anyone know anyone who has and who would be willing to contribute this?
4. Does anyone know anyone who has and who would be willing to do this for pay?

Wolfgang estimates that it would require 3 days of work to carry it to the finish line. I want him to remain focused on his current direction as his time is limited. Thus, the above priority list.

Feedback requested.

/cc @d-led @Framstag @kmruiz @aleixmorgadas @aleixyz @alexguzun @DaveMuirhead

**Comment by VaughnVernon** [comment]
This has been supported by the new CI pipeline: GitHub -> Travis -> Bintray.

For release procedures, see:
https://github.com/vlingo/vlingo-platform/blob/master/RELEASE_HOW_TO.md

**Comment by VaughnVernon** [comment]
This has been supported by the new CI pipeline: GitHub -> Travis -> Bintray.

For release procedures, see:
https://github.com/vlingo/vlingo-platform/blob/master/RELEASE_HOW_TO.md
