### ISSUE TITLE
An actor can be erroneous requested for a Java class type (not interface)

### ISSUE THREAD

**Issue by bwehrle** [vlingo/vlingo-actors#31]
Hi,
I made a simple coding mistake and tried to instantiate a proxy to an actor by class reference using the class of the "entity" and not the "protocol" (or interfaces definition).  This caused the Dynacompile code to try to create a proxy based on my entity class, which ended up being uncompilable.
I propose the actor proxy creation code checks via reflection that the java type being passed in is an interface, not a class type reference.

Any concerns with the proposed solution?  Otherwise I'll take a look at implementing this.

**Comment by d-led** [comment]
Try it. Looks good to me

**Comment by VaughnVernon** [comment]
> Any concerns with the proposed solution? Otherwise I'll take a look at implementing this.

I have fixed this inside `Stage`. The fix will be available later today.

**Comment by bwehrle** [comment]
Great- thanks for implementing a fix for this!

**Comment by bwehrle** [comment]
I checked this and it looks good, now throws an IllegalArgumentException.
