### ISSUE TITLE
how to use vlingo-actors ？

### ISSUE THREAD

**Issue by yuer2016** [vlingo/vlingo-actors#32]
I read the basic tutorial, but how to use it in a specific business scenario. Is there any more sample code? Thank you very much.

**Comment by VaughnVernon** [comment]
Several/Many examples here. Does this help?

https://github.com/vlingo/vlingo-examples

**Comment by d-led** [comment]
Depending on the business, here's the kind you might have had in mind https://github.com/kmruiz/vlingo-bank-example

If interfacing with other code is if concern, check out https://github.com/d-led/vlingo_experiments

As with any other technology, trying out the basics will guide one to an understanding how that could be applied in bigger context.

**Comment by yuer2016** [comment]
Very helpful, thank you very much. thanks your cool job ,This is a simple and elegant framework!
