### ISSUE TITLE
ProxyGenerator configuration shouldn't be static

### ISSUE THREAD

**Issue by eskatos** [vlingo/vlingo-actors#35]
Configuration of the `ProxyGenerator` happens via static `Properties`.

This forces consumers, e.g. build tools, to isolate its usage in separate classloaders in order to be able to safely run the proxy generator in parallel on multiple set of actors (think multi-module project build running in parallel).

If the `ProxyGenerator` configuration could be simply passed then this gymnastic wouldn't be required, possibly leading to better performance.

**Comment by VaughnVernon** [comment]
@eskatos Sorry for the hassles! The `ClassLoader` is now associated with each `World` as an instance variable. Does that work for you situation? The fix is intended for `0.8.0` available tomorrow.

**Comment by eskatos** [comment]
I should have stated the context in which the issue above takes place: a Gradle plugin that generates actor proxies at build time. There's no `World` there but a direct usage of `ProxyGenerator`, just like the maven plugin does.

**Comment by VaughnVernon** [comment]
@eskatos I could implement this quickly/easily for <= JDK 1.8 (our current baseline JDK). For JDK 1.9 and above I can't find much clear information as to how to dynamically set the classpath. Any suggestions?

From your experience, is this answer correct?

https://stackoverflow.com/questions/48322201/java-9-add-jar-dynamically-at-runtime/48323948#48323948

**Comment by eskatos** [comment]
I implemented what I had in mind in #37. There should not be any issues with Java >=9 with this approach. I hope it clarifies things a bit, let's discuss around the code.

**Comment by eskatos** [comment]
Fixed by #37, closing
