### ISSUE TITLE
ProxyGenerator should accept a classpath instead of a single classes directory

### ISSUE THREAD

**Issue by eskatos** [vlingo/vlingo-actors#36]
Currently, `ProxyGenerator` can be configured with the `proxy.generated.classes.main`  property. It is then interpreted as a path to a single directory.

It works in simple scenarios like single module maven builds or actor types not depending on other actor types declared in another module or source set.

The property should be a classpath instead, that is a set of paths to JARs and directories.

This would enable making the Maven plugin support generating proxies for actors that import types from dependencies (external or other modules) and actors in `src/test` that import types from `src/main`.

This would also enable making a Gradle plugin support the same plus multiple jvm languages projects because as opposed to Maven where everybody writes to `target/classes` in Gradle each compilation unit has its own output directory, no overlapping outputs.

**Comment by VaughnVernon** [comment]
@eskatos Ah, that's not what ` proxy.generated.classes.main` is for. That property points to the directory where the generated sources should be created. I see your point about classpath, however. I wonder though, if the classpath were set at runtime, wouldn't the `ProxyGenerator` see all dependencies that way?  Perhaps you are referring to the use of `vlingo-maven-plugin` to generate proxies. Either way, could you provide a bit more conceptual design for how you see this working?

**Comment by eskatos** [comment]
From my reading it's the `proxy.generated.sources.main` property that points to the directory where the generated sources should be created.

`proxy.generated.classes.main` is the one that is used for the `URLClassLoader` that `ProxyGenerator` uses to inspect protocols. What I'm after is a way to feed the `ProxyGenerator` with a classpath instead of a single directory.

**Comment by VaughnVernon** [comment]
@eskatos Ok, thanks for your patience. As stated in #35 I can implement as you request but I don't have experience with `ClassLoader` from JDK 1.9+. Any clues would be helpful. (Besides, I had no time today to research this beyond a few Google searches.)

**Comment by eskatos** [comment]
Fixed by #37, closing
