### ISSUE TITLE
Exceptions should never be suppressed

### ISSUE THREAD

**Issue by alanStrait** [vlingo/vlingo-actors#45]
In using vlingo for application development the default actor supervisor policy seems to cause exceptions to be lost without being logged.  While the documentation is clear that actor lifecycle methods should be overridden to understand why an actor has been stopped, it would be valuable for the default policy to, “log and stop” rather than just “stop.”

**Comment by VaughnVernon** [comment]
@alanStrait Thanks, this is good. Do you mean like this?

```
  protected void beforeRestart(final Throwable reason) {
    // override
    logger().log("Default recovery after: " + reason.getMessage(), reason);
    lifeCycle.afterStop(this);
  }
```

**Comment by alanStrait** [comment]
Yes, that would be helpful, it not a full stack trace (when in development mode).

**Comment by VaughnVernon** [comment]
@alanStrait Ok, will do. I think that all of the default supervisors log, but I may be wrong. If you can identify any supervisors missing logging I can fix those, too.

**Comment by VaughnVernon** [comment]
@alanStrait The `Actor` default recovery methods now implementing logging. Please test and close if you agree that it's fixed. (Again if you find other places that are missing essential logging please create and issue.)

**Comment by alanStrait** [comment]
Yes, that would be helpful, if not a full stack trace (for development mode).

Alan Strait | m.+1.720.840.8567

**Comment by VaughnVernon** [comment]
@alanStrait The full stacktrace should log/print with the standard logging. If you agree, please Close this issue. See:

https://github.com/vlingo/vlingo-actors/blob/e6926cdf0a12978b40a7c4ffa103eb720732f599/src/main/java/io/vlingo/actors/plugin/logging/jdk/JDKLogger.java#L72

**Comment by alanStrait** [comment]
After picking up the change I reverted some source code to expose an NPE that I would have hoped to be logged.  Unfortunately the behavior remains as before, no indication of what is wrong but also does not complete restful call.  I'd suggest closing this and perhaps I'll be able to collect more information that may be helpful as time goes on.

**Comment by VaughnVernon** [comment]
Implemented. There may be other issues with recovery that are app/service specific. Closing.
