### ISSUE TITLE
Log loses the context of caller

### ISSUE THREAD

**Issue by alexguzun** [vlingo/vlingo-actors#52]
Each log event loses the context of the caller: class, thread, method, MDC (Mapped Diagnostic Context) and most importantly the real time of the event. 

This occurs mostly due to the fact that the logging is done not by original Actor, but is sent to the `Slf4jLoggerActor` Actor, as a message. 

A possible solution is to craete a wrapper class, that encapsulates all required information. Something like `java.util.logging.LogRecord`.

**Comment by VaughnVernon** [comment]
We can have an implementation of Logger in the Actor that allows for MDC key-value setting and that is sent to the actor-based logger as a parameter. This will require additional methods on the interface to carry the MDC parameter. The Logger can be held on Environment.

**Comment by VaughnVernon** [comment]
@alexguzun If we were to create the wrapper as you suggest, what would be the default information that should be provided for each Actor? For example, should we show the fully-qualified classname or just the simple classname? If you could, please list the reasonable defaults and then also the necessary API for overriding any of the defaults and setting additional MDC information.

**Comment by alexguzun** [comment]
Each log event must capture:
- **Fully qualified name of class**. Slf4j allows configuring the output of class name. Users can configure to output just name. Example `%logger{36}`
- **Event timestamp**
- **Thread name**

For MDC, we can add this optional information: 
- **Actor name**
- **Actor address**
- **World name**
- **Stage name**

For actor logging, I would make sense to have the logging API defined in `io.vlingo.actors.Actor`.

**Comment by alexguzun** [comment]
Closed by #77
