### ISSUE TITLE
getting started sample seems outdated and got a logging problem

### ISSUE THREAD

**Issue by anderskristian** [vlingo/vlingo-actors#64]
I have tried to follow https://kalele.io/vlingo-actors-tutorial-1/

I see that the sample is not up to date with the sample in the samples. it just confuse me a little. Okay I made it work by taking the new code from the new samples.
So I learned something ... :-)

The logging has a problem. 
When I build from mvn clean the logging works.
When I run it the second time the logging is not shown...

I find that it is when the proxy classes are generated -- it works :-)
But when the proxy classes exists it does not work.
I cannot see the reason behind this?

I'm not giving up - I need to learn vlingo

**Comment by VaughnVernon** [comment]
@anderskristian Do you mind telling me what is wrong in the docs so I can update them? Thanks!

**Comment by anderskristian** [comment]
Tutorial  https://kalele.io/vlingo-actors-tutorial-1/ is based on version 0.4.8
Current version in sample in code base vlingo-examples/vlingo-actors-playground is very different.

The new version
1) does use World.startWithDefaults - so no property file is needed
2) and uses TestUntil - the 0.4.8 uses pauseThisThread 

A) as a beginner I find startWithDefaults easier..
B) I normally sits and use the new version when I study something - therefore it took me a little while to understand the changes from 0.4.8 version to 1.1.0

I did NOT say it doesn't work. 

The other part with missing log output  .. I have only tried in 1.1.0 - I have not tried 0.4.8
I saw your video from Berlin where you talk about the logging problem -- did not really look into it.

So that logging output is missing, when proxy classes has been created. It is just an observation. In a real program it will probably not be a problem.

**Comment by VaughnVernon** [comment]
@anderskristian This is where you want to read these days.

https://docs.vlingo.io/vlingo-actors

Also the logging "problem" you are seeing is most likely due to the `Logger` implementation being an actor and the actor has not processed all of its messages before the `World.terminate()` completes. It's possible that the proxy creation increases time for the `Logger` to process its messages. If you put a `Thread.sleep(1000)` before the `World.terminate()` the `Logger` will probably complete output of all log messages. (This is not something you should do in a production system, just something to prove to yourself that everything works as expected.)

**Comment by anderskristian** [comment]
I have tried to put Thread.sleep(1000) - it did not change the result
I will try again now. Just to make sure ..

**Comment by anderskristian** [comment]
This is my code and it does NOT log when proxy has been generated

`    @Test
    public void testPlayPingPong() {
        final World world = World.startWithDefaults("playground");
        final TestUntil until = TestUntil.happenings(1);
        final Pinger pinger = world.actorFor(Pinger.class, PingerActor.class, until);
        final Ponger ponger = world.actorFor(Ponger.class, PongerActor.class);

        pinger.ping(ponger);

        until.completes();
        try {
            TimeUnit.MILLISECONDS.sleep(1000);
        } catch (Exception e){
            System.out.println("aborted");
        }
        world.terminate();
    }
`

**Comment by VaughnVernon** [comment]
With clean test:

```
$ mvn clean test

Running playground.PlaygroundTest
18:48:58.791 [pool-2-thread-5] DEBUG io.vlingo.actors.Logger - playground.PingerActor - vlingo/actors: Generating proxy for main: playground.Pinger
18:48:59.267 [pool-2-thread-7] DEBUG io.vlingo.actors.Logger - playground.PongerActor - vlingo/actors: Generating proxy for main: playground.Ponger
18:48:59.347 [pool-2-thread-10] DEBUG io.vlingo.actors.Logger - playground.PingerActor - ping 1
18:48:59.348 [pool-2-thread-11] DEBUG io.vlingo.actors.Logger - playground.PongerActor - pong
18:48:59.348 [pool-2-thread-11] DEBUG io.vlingo.actors.Logger - playground.PingerActor - ping 2
18:48:59.348 [pool-2-thread-9] DEBUG io.vlingo.actors.Logger - playground.PongerActor - pong
18:48:59.348 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - playground.PingerActor - ping 3
18:48:59.349 [pool-2-thread-11] DEBUG io.vlingo.actors.Logger - playground.PongerActor - pong
18:48:59.349 [pool-2-thread-11] DEBUG io.vlingo.actors.Logger - playground.PingerActor - ping 4
18:48:59.349 [pool-2-thread-11] DEBUG io.vlingo.actors.Logger - playground.PongerActor - pong
18:48:59.349 [pool-2-thread-11] DEBUG io.vlingo.actors.Logger - playground.PingerActor - ping 5
18:48:59.349 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - playground.PongerActor - pong
18:48:59.349 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - playground.PingerActor - ping 6
18:48:59.349 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - playground.PongerActor - pong
18:48:59.349 [pool-2-thread-1] DEBUG io.vlingo.actors.Logger - playground.PingerActor - ping 7
18:48:59.349 [pool-2-thread-4] DEBUG io.vlingo.actors.Logger - playground.PongerActor - pong
18:48:59.349 [pool-2-thread-4] DEBUG io.vlingo.actors.Logger - playground.PingerActor - ping 8
18:48:59.349 [pool-2-thread-4] DEBUG io.vlingo.actors.Logger - playground.PongerActor - pong
18:48:59.350 [pool-2-thread-4] DEBUG io.vlingo.actors.Logger - playground.PingerActor - ping 9
18:48:59.350 [pool-2-thread-4] DEBUG io.vlingo.actors.Logger - playground.PongerActor - pong
18:48:59.350 [pool-2-thread-4] DEBUG io.vlingo.actors.Logger - playground.PingerActor - ping 10
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.879 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```
$ mvn test

With test (no clean):

Running playground.PlaygroundTest
18:49:08.673 [pool-2-thread-8] DEBUG io.vlingo.actors.Logger - playground.PingerActor - ping 1
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.327 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

Although all logs don't display the first one does. I promise it is just timing. Make your test sleep for 5 seconds. It really should work.

**Comment by d-led** [comment]
in case it helps, I've kept a version of "hello world" here: https://github.com/d-led/hello_vlingo

will update it to the latest version too to see if it still runs

**Comment by VaughnVernon** [comment]
Closing this issue. Please see docs.vlingo.io for up-to-date docs.
