### ISSUE TITLE
Using andThen on the completes returned from Actor.completes() throws UnsupportedOperationException exception

### ISSUE THREAD

**Issue by buritos** [vlingo/vlingo-actors#69]
```java
...
public Completes<Integer> boom() {
  return completes().with(1).andThen(one -> one + 1);
}
...
```
When boom is called on the actor proxy created via `World.actorFor` it throws:
```
java.lang.UnsupportedOperationException: null
	at io.vlingo.actors.ResultReturns.andThen(ResultReturns.java:38)
```
I was expecting a successful `Completes` with the `Integer` value `2` inside.

**Comment by VaughnVernon** [comment]
@buritos My feedback is in Slack. If you want to condense any of that and put it here for later reference that's fine.

**Comment by VaughnVernon** [comment]
This was fixed by the following and some redesign.

https://github.com/vlingo/vlingo-common/issues/12
