### ISSUE TITLE
Fails with LinkageError

### ISSUE THREAD

**Issue by buritos** [vlingo/vlingo-actors#70]
https://github.com/vlingo/vlingo-actors/blob/68f9762a9e96367ab8a13bd3a507624887542788/src/test/java/io/vlingo/actors/ActorEnvironmentTest.java#L53

**Comment by VaughnVernon** [comment]
This was a problem with the `World` `ClassLoader` used by `vlingo-lattice` and was fixed there by the following.

https://github.com/vlingo/vlingo-lattice/blob/75893168a726b9851e309ffeb6c22ac1f1b37436/src/main/java/io/vlingo/actors/Grid.java#L208
